DROP TABLE IF EXISTS [PERUBAHAN_STATUSWN];
DROP TABLE IF EXISTS [PERUBAHAN_NAMA];
DROP TABLE IF EXISTS [KEMATIAN];
DROP TABLE IF EXISTS [PERPINDAHAN];
DROP TABLE IF EXISTS [PERCERAIAN];
DROP TABLE IF EXISTS [PERISTIWA_PENTING];
DROP TABLE IF EXISTS [PENYAKIT];
DROP TABLE IF EXISTS [KESEHATAN];
DROP TABLE IF EXISTS [PENDUDUK_PEKERJAAN];
DROP TABLE IF EXISTS [PEKERJAAN];
DROP TABLE IF EXISTS [BARANG_MEWAH];
DROP TABLE IF EXISTS [INVESTASI];
DROP TABLE IF EXISTS [KENDARAAN];
DROP TABLE IF EXISTS [PROPERTI];
DROP TABLE IF EXISTS [KEKAYAAN];
DROP TABLE IF EXISTS [BPJS];
DROP TABLE IF EXISTS [PENDIDIKAN];
DROP TABLE IF EXISTS [PENDUDUK];
DROP TABLE IF EXISTS [KARTU_KELUARGA];

CREATE TABLE [KARTU_KELUARGA] (
	[NoKK] CHAR (16),
	[StatusAnggota] VARCHAR (10),
	[Nama_Ayah] VARCHAR (32),
	[Nama_Ibu] VARCHAR (32),

	PRIMARY KEY ([NoKK], [StatusAnggota]),
);

CREATE TABLE [PENDUDUK] (
	[NIK] CHAR (16),
	[NamaLengkap] VARCHAR (64),
	[TTL] VARCHAR (30),
	[Tempat_Lahir] VARCHAR (15),
	[Tanggal_Lahir] DATE,
	[NoKK] CHAR (16),
	[StatusAnggota] VARCHAR (10),
	[Alamat_Jalan] VARCHAR (32),
	[Alamat_RTRW] CHAR (11),
	[Alamat_Desa] VARCHAR (32),
	[Alamat_Kecamatan] VARCHAR (32),
	[Alamat_Kabupaten] VARCHAR (32),
	[Alamat_Provinsi] VARCHAR (32),
	[Alamat_KodePos] CHAR (5),
	[JenisKelamin] VARCHAR (10),
	[GolDarah] VARCHAR (2),
	[Kewarganegaraan] VARCHAR (32),
	[StatusPernikahan] VARCHAR (15),
	[Usia] INT,
	
	PRIMARY KEY ([NIK]),
	FOREIGN KEY ([NoKK], [StatusAnggota]) REFERENCES [KARTU_KELUARGA]([NoKK], [StatusAnggota])
);

CREATE TABLE [PENDIDIKAN] (
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[NIK] CHAR (16),
	[PendidikanTerakhir] VARCHAR (10),
	[PendidikanTerakhir_NamaInstansi] VARCHAR (15),
	[PendidikanTerakhir_Lokasi] VARCHAR (64),
	[PendidikanTerakhir_TahunLulus] INT,
	[PendidikanSekarang] VARCHAR (10),
	[PendidikanSekarang_NamaInstansi] VARCHAR (15),
	[PendidikanSekarang_Lokasi] VARCHAR (64),

	PRIMARY KEY ([ID]),
	FOREIGN KEY ([NIK]) REFERENCES [PENDUDUK]([NIK])
);

CREATE TABLE [BPJS] (
	[NoPeserta] VARCHAR (16),
	[NIK] CHAR (16),
	[Kelas] VARCHAR (10),

	PRIMARY KEY ([NoPeserta]),
	FOREIGN KEY ([NIK]) REFERENCES [PENDUDUK]([NIK])
);

CREATE TABLE [KEKAYAAN] (
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[NIK] CHAR (16),
	[PendapatanPerTahun] MONEY,

	PRIMARY KEY ([ID]),
	FOREIGN KEY ([NIK]) REFERENCES [PENDUDUK]([NIK])
);

CREATE TABLE [PROPERTI] (
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[KekayaanID] UNIQUEIDENTIFIER,
	[Jenis] VARCHAR (15),
	[Luas] INT,
	[Lokasi] VARCHAR (128),
	[Harga] MONEY,

	PRIMARY KEY ([ID], [KekayaanID]),
	FOREIGN KEY ([KekayaanID]) REFERENCES [KEKAYAAN]([ID])
);

CREATE TABLE [KENDARAAN] (
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[KekayaanID] UNIQUEIDENTIFIER,
	[Jenis_Nama] VARCHAR (15),
	[Jenis_Tipe] VARCHAR (15),
	[Jenis_CC] INT,
	[Jenis_BB] VARCHAR (17),
	[NJKB] MONEY,
	[Tahun] INT,

	PRIMARY KEY ([ID], [KekayaanID]),
	FOREIGN KEY ([KekayaanID]) REFERENCES [KEKAYAAN]([ID])
);

CREATE TABLE [INVESTASI] (
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[KekayaanID] UNIQUEIDENTIFIER,
	[Jenis] VARCHAR (15),
	[Dividen] MONEY,

	PRIMARY KEY ([ID], [KekayaanID]),
	FOREIGN KEY ([KekayaanID]) REFERENCES [KEKAYAAN]([ID])
);

CREATE TABLE [BARANG_MEWAH] (
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[KekayaanID] UNIQUEIDENTIFIER,
	[Jenis] VARCHAR (15),
	[Nilai] MONEY,

	PRIMARY KEY ([ID], [KekayaanID]),
	FOREIGN KEY ([KekayaanID]) REFERENCES [KEKAYAAN]([ID])
);

CREATE TABLE [PEKERJAAN] (
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[NIK] CHAR (16),
	[KekayaanID] UNIQUEIDENTIFIER,
	[NamaPekerjaan] VARCHAR (20),
	[Jenis] VARCHAR (20),
	[GajiPerTahun] MONEY,
	[Lokasi] VARCHAR (128),
	[Perusahaan] VARCHAR (20),

	PRIMARY KEY ([ID]),
	FOREIGN KEY ([NIK]) REFERENCES [PENDUDUK]([NIK]),
	FOREIGN KEY ([KekayaanID]) REFERENCES [KEKAYAAN]([ID])
);

CREATE TABLE [PENDUDUK_PEKERJAAN] (
	[NIK] CHAR (16),
	[PekerjaanID] UNIQUEIDENTIFIER,
	[WaktuPerjalanan] INT,
	[JamKerjaPerMinggu] INT,

	PRIMARY KEY ([NIK], [PekerjaanID]),
	FOREIGN KEY ([NIK]) REFERENCES [PENDUDUK]([NIK]),
	FOREIGN KEY ([PekerjaanID]) REFERENCES [PEKERJAAN]([ID])
);

CREATE TABLE [KESEHATAN] (
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[NIK] CHAR (16),
	[Alergi] VARCHAR (15),
	[Vaksinasi] VARCHAR (15),
	[Turunan] VARCHAR (15),
	[Disabilitas] VARCHAR (15),
	[Fisik_Tinggi] INT,
	[Fisik_BeratBadan] INT,

	PRIMARY KEY ([ID]),
	FOREIGN KEY ([NIK]) REFERENCES [PENDUDUK]([NIK])
);

CREATE TABLE [PENYAKIT] (
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[KesehatanID] UNIQUEIDENTIFIER,
	[TanggalDiagnosa] DATE,
	[Status] VARCHAR (12),
	[TanggalSembuh] DATE,

	PRIMARY KEY ([ID]),
	FOREIGN KEY ([KesehatanID]) REFERENCES [KESEHATAN]([ID])
);

CREATE TABLE [PERISTIWA_PENTING] (
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[NIK] CHAR (16),
	[TanggalTerjadi] DATE,
	[NamaPeristiwa] VARCHAR (64),

	PRIMARY KEY ([ID]),
	FOREIGN KEY ([NIK]) REFERENCES [PENDUDUK]([NIK])
);

CREATE TABLE [PERCERAIAN] (
	[PeristiwaID] UNIQUEIDENTIFIER,
	[StatusGugatan] VARCHAR (12),
	[Alasan] VARCHAR (128),

	PRIMARY KEY ([PeristiwaID]),
	FOREIGN KEY ([PeristiwaID]) REFERENCES [PERISTIWA_PENTING]([ID])
);

CREATE TABLE [PERPINDAHAN] (
	[PeristiwaID] UNIQUEIDENTIFIER,
	[Asal] VARCHAR (15),
	[Tujuan] VARCHAR (15),

	PRIMARY KEY ([PeristiwaID]),
	FOREIGN KEY ([PeristiwaID]) REFERENCES [PERISTIWA_PENTING]([ID])
);

CREATE TABLE [KEMATIAN] (
	[PeristiwaID] UNIQUEIDENTIFIER,
	[Lokasi] VARCHAR (15),
	[Alasan] VARCHAR (128),

	PRIMARY KEY ([PeristiwaID]),
	FOREIGN KEY ([PeristiwaID]) REFERENCES [PERISTIWA_PENTING]([ID])
);

CREATE TABLE [PERUBAHAN_NAMA] (
	[PeristiwaID] UNIQUEIDENTIFIER,
	[NamaBaru] VARCHAR (64),
	[Alasan] VARCHAR (128),

	PRIMARY KEY ([PeristiwaID]),
	FOREIGN KEY ([PeristiwaID]) REFERENCES [PERISTIWA_PENTING]([ID])
);

CREATE TABLE [PERUBAHAN_STATUSWN] (
	[PeristiwaID] UNIQUEIDENTIFIER,
	[StatusBaru] VARCHAR (20),
	[Alasan] VARCHAR (128),

	PRIMARY KEY ([PeristiwaID]),
	FOREIGN KEY ([PeristiwaID]) REFERENCES [PERISTIWA_PENTING]([ID])
);