DROP TABLE IF EXISTS [PERUBAHAN_STATUSWN];
DROP TABLE IF EXISTS [PERUBAHAN_NAMA];
DROP TABLE IF EXISTS [KEMATIAN];
DROP TABLE IF EXISTS [PERPINDAHAN];
DROP TABLE IF EXISTS [PERCERAIAN];
DROP TABLE IF EXISTS [PERISTIWA_PENTING];
DROP TABLE IF EXISTS [PENYAKIT];
DROP TABLE IF EXISTS [KESEHATAN];
DROP TABLE IF EXISTS [PENDUDUK_PEKERJAAN];
DROP TABLE IF EXISTS [PEKERJAAN];
DROP TABLE IF EXISTS [BARANG_MEWAH];
DROP TABLE IF EXISTS [INVESTASI];
DROP TABLE IF EXISTS [KENDARAAN];
DROP TABLE IF EXISTS [PROPERTI];
DROP TABLE IF EXISTS [KEKAYAAN];
DROP TABLE IF EXISTS [BPJS];
DROP TABLE IF EXISTS [PENDIDIKAN];
DROP TABLE IF EXISTS [PENDUDUK];
DROP TABLE IF EXISTS [KARTU_KELUARGA];

CREATE TABLE [KARTU_KELUARGA] (
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[NoKK] NVARCHAR (16),
	[StatusAnggota] NVARCHAR (10),
	[Nama_Ayah] NVARCHAR (32),
	[Nama_Ibu] NVARCHAR (32),

	PRIMARY KEY ([ID]),
);

CREATE TABLE [PENDUDUK] (
	[NIK] NVARCHAR (16),
	[KKID] UNIQUEIDENTIFIER,
	[NamaLengkap] NVARCHAR (64),
	[TTL] NVARCHAR (30),
	[Tempat_Lahir] NVARCHAR (15),
	[Tanggal_Lahir] NVARCHAR (15),
	[Alamat] NVARCHAR (128),
	[Alamat_Jalan] NVARCHAR (32),
	[Alamat_RTRW] NVARCHAR (16),
	[Alamat_Desa] NVARCHAR (16),
	[Alamat_Kecamatan] NVARCHAR (16),
	[Alamat_Kabupaten] NVARCHAR (16),
	[Alamat_Provinsi] NVARCHAR (16),
	[Alamat_KodePos] NVARCHAR (5),
	[JenisKelamin] NVARCHAR (10),
	[GolDarah] NVARCHAR (2),
	[Kewarganegaraan] NVARCHAR (20),
	[StatusPernikahan] NVARCHAR (15),
	[Usia] INT,
	
	PRIMARY KEY ([NIK]),
	FOREIGN KEY ([KKID]) REFERENCES [KARTU_KELUARGA]([ID])
);

CREATE TABLE [PENDIDIKAN] (
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[NIK] NVARCHAR (16),
	[PendidikanTerakhir] NVARCHAR (10),
	[PendidikanTerakhir_NamaInstansi] NVARCHAR (15),
	[PendidikanTerakhir_Lokasi] NVARCHAR (64),
	[PendidikanSekasrang] NVARCHAR (10),
	[PendidikanSekarang_NamaInstansi] NVARCHAR (15),
	[PendidikanSekarang_Lokasi] NVARCHAR (64),
	[Tahun_SD] INT,
	[Tahun_SMP] INT,
	[Tahun_SMA] INT,
	[Tahun_ST] INT,

	PRIMARY KEY ([ID]),
	FOREIGN KEY ([NIK]) REFERENCES [PENDUDUK]([NIK])
);

CREATE TABLE [BPJS] (
	[NoPeserta] NVARCHAR (16),
	[NIK] NVARCHAR (16),
	[Kelas] NVARCHAR (10),

	PRIMARY KEY ([NoPeserta]),
	FOREIGN KEY ([NIK]) REFERENCES [PENDUDUK]([NIK])
);

CREATE TABLE [KEKAYAAN] (
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[NIK] NVARCHAR (16),
	[PendapatanPerTahun] MONEY,

	PRIMARY KEY ([ID]),
	FOREIGN KEY ([NIK]) REFERENCES [PENDUDUK]([NIK])
);

CREATE TABLE [PROPERTI] (
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[KekayaanID] UNIQUEIDENTIFIER,
	[Jenis] NVARCHAR (15),
	[Luas] INT,
	[Lokasi] NVARCHAR (128),
	[Harga] MONEY,

	PRIMARY KEY ([ID], [KekayaanID]),
	FOREIGN KEY ([KekayaanID]) REFERENCES [KEKAYAAN]([ID])
);

CREATE TABLE [KENDARAAN] (
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[KekayaanID] UNIQUEIDENTIFIER,
	[Jenis_Nama] NVARCHAR (15),
	[Jenis_Tipe] NVARCHAR (15),
	[Jenis_CC] INT,
	[Jenis_BB] NVARCHAR (17),
	[NJKB] MONEY,
	[Tahun] INT,

	PRIMARY KEY ([ID], [KekayaanID]),
	FOREIGN KEY ([KekayaanID]) REFERENCES [KEKAYAAN]([ID])
);

CREATE TABLE [INVESTASI] (
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[KekayaanID] UNIQUEIDENTIFIER,
	[Jenis] NVARCHAR (15),
	[Dividen] MONEY,

	PRIMARY KEY ([ID], [KekayaanID]),
	FOREIGN KEY ([KekayaanID]) REFERENCES [KEKAYAAN]([ID])
);

CREATE TABLE [BARANG_MEWAH] (
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[KekayaanID] UNIQUEIDENTIFIER,
	[Jenis] NVARCHAR (15),
	[Nilai] MONEY,

	PRIMARY KEY ([ID], [KekayaanID]),
	FOREIGN KEY ([KekayaanID]) REFERENCES [KEKAYAAN]([ID])
);

CREATE TABLE [PEKERJAAN] (
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[NIK] NVARCHAR (16),
	[KekayaanID] UNIQUEIDENTIFIER,
	[NamaPekerjaan] NVARCHAR (20),
	[Jenis] NVARCHAR (20),
	[GajiPerTahun] MONEY,
	[Lokasi] NVARCHAR (128),
	[Perusahaan] NVARCHAR (20),

	PRIMARY KEY ([ID]),
	FOREIGN KEY ([NIK]) REFERENCES [PENDUDUK]([NIK]),
	FOREIGN KEY ([KekayaanID]) REFERENCES [KEKAYAAN]([ID])
);

CREATE TABLE [PENDUDUK_PEKERJAAN] (
	[NIK] NVARCHAR (16),
	[PekerjaanID] UNIQUEIDENTIFIER,
	[WaktuPerjalanan] INT,
	[JamKerjaPerMinggu] INT,

	PRIMARY KEY ([NIK], [PekerjaanID]),
	FOREIGN KEY ([NIK]) REFERENCES [PENDUDUK]([NIK]),
	FOREIGN KEY ([PekerjaanID]) REFERENCES [PEKERJAAN]([ID])
);

CREATE TABLE [KESEHATAN] (
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[NIK] NVARCHAR (16),
	[Alergi] NVARCHAR (15),
	[Vaksinasi] NVARCHAR (15),
	[Turunan] NVARCHAR (15),
	[Disabilitas] NVARCHAR (15),
	[Fisik_Tinggi] INT,
	[Fisik_BeratBadan] INT,

	PRIMARY KEY ([ID]),
	FOREIGN KEY ([NIK]) REFERENCES [PENDUDUK]([NIK])
);

CREATE TABLE [PENYAKIT] (
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[KesehatanID] UNIQUEIDENTIFIER,
	[TanggalDiagnosa] DATE,
	[Status] NVARCHAR (12),
	[TanggalSembuh] DATE,

	PRIMARY KEY ([ID]),
	FOREIGN KEY ([KesehatanID]) REFERENCES [KESEHATAN]([ID])
);

CREATE TABLE [PERISTIWA_PENTING] (
	[ID] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[NIK] NVARCHAR (16),
	[TanggalTerjadi] DATE,
	[NamaPeristiwa] NVARCHAR (64),

	PRIMARY KEY ([ID]),
	FOREIGN KEY ([NIK]) REFERENCES [PENDUDUK]([NIK])
);

CREATE TABLE [PERCERAIAN] (
	[PeristiwaID] UNIQUEIDENTIFIER,
	[StatusGugatan] NVARCHAR (12),
	[Alasan] NVARCHAR (128),

	PRIMARY KEY ([PeristiwaID]),
	FOREIGN KEY ([PeristiwaID]) REFERENCES [PERISTIWA_PENTING]([ID])
);

CREATE TABLE [PERPINDAHAN] (
	[PeristiwaID] UNIQUEIDENTIFIER,
	[Asal] NVARCHAR (15),
	[Tujuan] NVARCHAR (15),

	PRIMARY KEY ([PeristiwaID]),
	FOREIGN KEY ([PeristiwaID]) REFERENCES [PERISTIWA_PENTING]([ID])
);

CREATE TABLE [KEMATIAN] (
	[PeristiwaID] UNIQUEIDENTIFIER,
	[Lokasi] NVARCHAR (15),
	[Alasan] NVARCHAR (128),

	PRIMARY KEY ([PeristiwaID]),
	FOREIGN KEY ([PeristiwaID]) REFERENCES [PERISTIWA_PENTING]([ID])
);

CREATE TABLE [PERUBAHAN_NAMA] (
	[PeristiwaID] UNIQUEIDENTIFIER,
	[NamaBaru] NVARCHAR (64),
	[Alasan] NVARCHAR (128),

	PRIMARY KEY ([PeristiwaID]),
	FOREIGN KEY ([PeristiwaID]) REFERENCES [PERISTIWA_PENTING]([ID])
);

CREATE TABLE [PERUBAHAN_STATUSWN] (
	[PeristiwaID] UNIQUEIDENTIFIER,
	[StatusBaru] NVARCHAR (20),
	[Alasan] NVARCHAR (128),

	PRIMARY KEY ([PeristiwaID]),
	FOREIGN KEY ([PeristiwaID]) REFERENCES [PERISTIWA_PENTING]([ID])
);