DELETE FROM [KELAHIRAN];
DELETE FROM [PENGANGKATAN_ANAK];
DELETE FROM [PERUBAHAN_STATUSWN];
DELETE FROM [PERUBAHAN_NAMA];
DELETE FROM [KEMATIAN];
DELETE FROM [PERPINDAHAN];
DELETE FROM [PERCERAIAN];
DELETE FROM [PERISTIWA_PENTING];
DELETE FROM [PENYAKIT];
DELETE FROM [KESEHATAN];
DELETE FROM [MEMILIKI_PEKERJAAN];
DELETE FROM [PEKERJAAN];
DELETE FROM [BARANG_MEWAH];
DELETE FROM [INVESTASI];
DELETE FROM [KENDARAAN];
DELETE FROM [PROPERTI];
DELETE FROM [KEKAYAAN];
DELETE FROM [WARGA_ASING];
DELETE FROM [BPJS];
DELETE FROM [PENDIDIKAN];
DELETE FROM [PENDUDUK];
DELETE FROM [KARTU_KELUARGA];

INSERT INTO [PENDUDUK] ([NIK])
VALUES
('3302202801040003');

SELECT * FROM PENDUDUK

