USE KEPENDUDUKAN

DROP TRIGGER IF EXISTS trg_penduduk_usia;
DROP TRIGGER IF EXISTS trg_kekayaan_gaji;

GO
CREATE TRIGGER trg_penduduk_usia
ON PENDUDUK
AFTER INSERT, UPDATE
AS
BEGIN
    UPDATE PENDUDUK
    SET Usia = DATEDIFF(year, INSERTED.Tanggal_Lahir, CURRENT_TIMESTAMP)
    FROM PENDUDUK
    JOIN INSERTED ON PENDUDUK.NIK = INSERTED.NIK;
END;


GO
CREATE TRIGGER trg_kekayaan_gaji
ON PEKERJAAN
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
	UPDATE KEKAYAAN
    SET PendapatanPerTahun = (
        SELECT SUM(P.GajiPerTahun)
        FROM PEKERJAAN P
        WHERE P.KekayaanID = KEKAYAAN.ID
    )
    WHERE ID IN (SELECT KekayaanID FROM INSERTED);
END; 